package com.popomusic.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.popomusic.bean.MusicBean;
import com.popomusic.bean.SearchNameBean;

import com.popomusic.bean.MusicBeanDao;
import com.popomusic.bean.SearchNameBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicBeanDaoConfig;
    private final DaoConfig searchNameBeanDaoConfig;

    private final MusicBeanDao musicBeanDao;
    private final SearchNameBeanDao searchNameBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicBeanDaoConfig = daoConfigMap.get(MusicBeanDao.class).clone();
        musicBeanDaoConfig.initIdentityScope(type);

        searchNameBeanDaoConfig = daoConfigMap.get(SearchNameBeanDao.class).clone();
        searchNameBeanDaoConfig.initIdentityScope(type);

        musicBeanDao = new MusicBeanDao(musicBeanDaoConfig, this);
        searchNameBeanDao = new SearchNameBeanDao(searchNameBeanDaoConfig, this);

        registerDao(MusicBean.class, musicBeanDao);
        registerDao(SearchNameBean.class, searchNameBeanDao);
    }
    
    public void clear() {
        musicBeanDaoConfig.clearIdentityScope();
        searchNameBeanDaoConfig.clearIdentityScope();
    }

    public MusicBeanDao getMusicBeanDao() {
        return musicBeanDao;
    }

    public SearchNameBeanDao getSearchNameBeanDao() {
        return searchNameBeanDao;
    }

}
