package com.popomusic.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.popomusic.bean.MusicBean;
import com.popomusic.bean.SearchNameBean;
import com.popomusic.videoModel.VideoBean;

import com.popomusic.bean.MusicBeanDao;
import com.popomusic.bean.SearchNameBeanDao;
import com.popomusic.videoModel.VideoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicBeanDaoConfig;
    private final DaoConfig searchNameBeanDaoConfig;
    private final DaoConfig videoBeanDaoConfig;

    private final MusicBeanDao musicBeanDao;
    private final SearchNameBeanDao searchNameBeanDao;
    private final VideoBeanDao videoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicBeanDaoConfig = daoConfigMap.get(MusicBeanDao.class).clone();
        musicBeanDaoConfig.initIdentityScope(type);

        searchNameBeanDaoConfig = daoConfigMap.get(SearchNameBeanDao.class).clone();
        searchNameBeanDaoConfig.initIdentityScope(type);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        musicBeanDao = new MusicBeanDao(musicBeanDaoConfig, this);
        searchNameBeanDao = new SearchNameBeanDao(searchNameBeanDaoConfig, this);
        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);

        registerDao(MusicBean.class, musicBeanDao);
        registerDao(SearchNameBean.class, searchNameBeanDao);
        registerDao(VideoBean.class, videoBeanDao);
    }
    
    public void clear() {
        musicBeanDaoConfig.clearIdentityScope();
        searchNameBeanDaoConfig.clearIdentityScope();
        videoBeanDaoConfig.clearIdentityScope();
    }

    public MusicBeanDao getMusicBeanDao() {
        return musicBeanDao;
    }

    public SearchNameBeanDao getSearchNameBeanDao() {
        return searchNameBeanDao;
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

}
